Feature/sprint1
JosimarBazilio/cardapio-digital-api pull request #1
Opened 2023-04-10 18:46 UTC by Ueverson

O que fiz?

Alterei o retorno do método autenticar cliente, para me retornar como json o webtoken
Adicionei validação caso o token chega undefined para não quebrar

2023-04-11 23:13 UTC, Koemyy requested changes

2023-04-11 23:13 UTC, Koemyy commented on src/modulos/actors/useCase/AutenticarClienteUseCase.ts
> +            throw new Error("invalido token");
Troca a mensagem pra Token invalido

2023-04-11 23:13 UTC, JosimarBazilio approved these changes

2023-04-16 15:25 UTC, Koemyy approved these changes

2023-04-16 17:33 UTC, merged